### ISSUE TITLE
SPA.addFractionOfDay() could fail on DST on/off days

### ISSUE THREAD

**Issue by KlausBrunner** [KlausBrunner/solarpositioning#10]

**Comment by hurzl** [comment]
Is this why today (first DST off day) sunrise and sunset are calculated 1 hour too early?

**Comment by KlausBrunner** [comment]
Please provide an actual test case for this. As a minimum, what lat/lon are we talking about, which timezone are you using as input? It's difficult to reproduce this otherwise, and I'm not going to accept a pull request without so much as a bug description or, ideally, a failing test case that it fixes.

**Comment by hurzl** [comment]
The cases I told you above, but yes I forgot the timezone which is CET.

**Comment by KlausBrunner** [comment]
Actually, this still needs a bit more tests for locations far away from UTC.
