### ISSUE TITLE
Sun transit date even when it is arctic night

### ISSUE THREAD

**Issue by errorscript** [KlausBrunner/solarpositioning#18]
On SPA.calculateSunriseTransitSet, sun transit is calculated even when there is no sunrise nor sunset and that it is the night (case when the position is inside the Arctic circle).

`GregorianCalendar cal = new GregorianCalendar(TimeZone.getTimeZone(ZoneId.of("Europe/Paris")));`
`cal.set(Calendar.YEAR, 2017);`
`cal.set(Calendar.DAY_OF_YEAR, 01);`
`SPA.calculateSunriseTransitSet(cal, 78., // latitude`
`    16., //Longitude`
`    DeltaT.estimate(cal)); // delta T`

A simple correction could be to return null for sun transit when : 
`final boolean noDay = (acosArg > 1.0);` 

Or if this behaviour is correct for you, can we get another method to get information on if there is a day or not.

**Comment by KlausBrunner** [comment]
I don't consider this a bug and will stick with the original SPA behaviour here. Even when the sun isn't considered to rise above the horizon on a given day, there is still a time when the sun crosses the observer's meridian. Sunrise/sunset fields will be null in that case, as documented.

**Comment by KlausBrunner** [comment]
On second thought, I do get the problem that you can't easily find out whether a case like this is "all night" or "all day" with the current API. You'd have to check the elevation at solar noon, which is clunky.
