### ISSUE TITLE
Regarding the steps of usage of this library

### ISSUE THREAD

**Issue by Shaunak-2** [klausbrunner/solarpositioning#39]
I am a new person in the java dev area and I wanted to use the repo in my project but i am confused about how to use the library what things do i need to have installed and do i need to make a jar file of the library could you please guide me for the same

**Comment by klausbrunner** [comment]
I'd suggest reading up on build systems like Maven and Gradle, which help you manage dependencies in your projects, and are well-supported in Java IDEs. Once you have a basic understanding of this, adding the library should be very easy.

**Comment by Shaunak-2** [comment]
Thank you for your response I was successful in using the library thank you
very much
