### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mtrevisan** [klausbrunner/solarpositioning#40]
Hi, there is a bug on file SPA.java, line 575

this one

``` pow(jd.julianCentury(), 2) / 38710000); ```

should be

``` pow(jd.julianCentury(), 3) / 38710000); ```

**Comment by klausbrunner** [comment]
Thanks for the report, @mtrevisan. This is indeed a deviation from the published algorithm. Do you happen to have a test case where this causes a significant difference?

**Comment by mtrevisan** [comment]
Sadly, no, I have no test cases for that.
But since we are talking of an error of about 0.0002°, give or take, I think this error is negligible.

**Comment by klausbrunner** [comment]
I guess we'd have to travel a bit into the future to see any effect of ^3 vs ^2, but it's a bug nonetheless. Thanks for the sharp-eyed report!
